services:
  - type: web
    name: BCU-Backend
    serviceId: srv-d1nuu9er433s738moo50  # <-- replace with actual ID
    env: node
    branch: master
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        sync: false
      - key: DB_URL
        sync: false
      - key: API
        sync: false
